-- 스키마 생성
CREATE DATABASE IF NOT EXISTS member;
CREATE DATABASE IF NOT EXISTS coupon;
CREATE DATABASE IF NOT EXISTS payment;
CREATE DATABASE IF NOT EXISTS class;
CREATE DATABASE IF NOT EXISTS chat;
CREATE DATABASE IF NOT EXISTS `rank`;

GRANT ALL PRIVILEGES ON *.* TO 'chunsun'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;