server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth-service/**

        - id: member-service
          uri: http://localhost:8082
          predicates:
            - Path=/member-service/**

        - id: coupon-service
          uri: http://localhost:8083
          predicates:
            - Path=/coupon-service/**

        - id: rank-service
          uri: http://localhost:8084
          predicates:
            - Path=/rank-service/**

        - id: payment-service
          uri: http://localhost:8085
          predicates:
            - Path=/payment-service/**

        - id: class-service
          uri: http://localhost:8086
          predicates:
            - Path=/class-service/**

        - id: chat-service
          uri: http://localhost:8087
          predicates:
            - Path=/chat-service/**