server:
  port: 0

spring:
  application:
    name: class-service

  datasource:
    url: jdbc:mysql://chunsun-db:3306/class?serverTimezone=UTC&characterEncoding=UTF-8

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  kafka:
    bootstrap-servers: kafka1:9092, kafka2:9092, kafka3:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      delivery.timeout.ms: 3000
      acks: all
      properties:
        spring.json.add.type.headers: true