server:
  port: 0

spring:
  application:
    name: member-service

  datasource:
    url: jdbc:mysql://chunsun-db:3306/member?serverTimezone=UTC&characterEncoding=UTF-8

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  sql:
    init:
      mode: always  # 애플리케이션 시작 시 SQL 스크립트 실행 가능

  hikari:
    maximum-pool-size: 10  # 커넥션 풀 크기 설정

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      region:
        static: ${AWS_REGION}
      s3:
        bucket: ${AWS_BUCKET}
      stack:
        auto: false

  servlet:
    multipart:
      enabled: true
      max-request-size: 10MB
      max-file-size: 5MB