server:
  port: 0

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: kafka1:9092, kafka2:9092, kafka3:9092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: "com.chunsun.notificationservice.application.dto.NotificationDto$RequestDto"
    listener:
      ack-mode: manual_immediate

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.kafka: DEBUG
    org.springframework.data.mongodb: DEBUG
    com.chunsun.notificationservice: DEBUG

mongodb:
  notification:
    expire: 2592000

sse:
  subscribe:
    timeout: 3600000

